name: gene
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - scikit-learn
  - requests
  - beautifulsoup4
  - psutil
  - pip:
    - torch==2.5.1+cu121
    - torchvision==0.20.1+cu121
    - torchaudio==2.5.1+cu121
    - transformers==4.40.2
    - sentence-transformers==2.2.2
    - accelerate>=0.20.0
    - mygene>=3.2.2
    - huggingface-hub==0.22.2
    - tokenizers==0.19.1
